services:
  express-server:
    build:
      context: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - express-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - express-network
    depends_on:
      - express-server

networks:
  express-network:
    driver: bridge
